spring.application.name=demo
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ===========================
# CONFIGURACIÓN H2
# ===========================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===========================
# CONFIGURACIÓN JPA
# ===========================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# CONSOLA H2 (para ver tu BD)
# ===========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console